module.exports = {
   jwtSecretKey: '',
   database: 'mrpizza',
   sqlHost: 'localhost',
   sqlAuthUser: 'mrPizzaAuth',
   sqlAuthPw: '',
   sqlVisitorUser: 'mrPizzaVisitor',
   sqlVisitorPw: '',
   sqlCustomerUser: 'mrPizzaCustomer',
   sqlCustomerPw: '',
   sqlEmployeeUser: 'mrPizzaEmployee',
   sqlEmployeePw: '',
   sqlAdminUser: 'mrPizzaAdmin',
   sqlAdminPw: '',
}
